FROM ibmjava:latest
ADD ./target/Dollar-Bank-Eureka-Gateway-0.0.1-SNAPSHOT.jar Dollar-Bank-Eureka-Gateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java", "-jar", "Dollar-Bank-Eureka-Gateway-0.0.1-SNAPSHOT.jar" ]